### ISSUE TITLE
Memory leak in PersistentPullingAgent

### ISSUE THREAD

**Issue by yoniabrahamy** [dotnet/orleans#1160]
Hi all,
We are currently working with a Kafka based persistent stream provider. In our system, each queue retains a large amount of messages in its cache. In our Persistent Stream implementation, our cache has a time guarantee. This means it will keep messages in the cache in order to maintain a certain time guarantee, even if these messages have already been consumed (this is done for rewinding purposes).
Currently, in the implementation of `PersistentStreamPullingAgent`, each pulling agent has a queue cache that it works with.

During stress testing we noticed that when there is pulling agents redistribution (for example: we were working for 10 minutes with a single silo and then put up 2 more silos in the cluster), the queue cache is not being collected by the GC (even though the pulling agent has shut down). After looking into it with memory debugging tools, we saw that there is a reference to the queue cache here:

```c#
IntValueStatistic.FindOrCreate(new StatisticName(StatisticNames.STREAMS_PERSISTENT_STREAM_QUEUE_CACHE_SIZE, statUniquePostfix), () => queueCache !=null ? queueCache.Size : 0);
```
(PersistentPullingAgent.cs line 92)

This line means that the IntValueStatistic keeps a reference to the queue cache and prevents the GC from collecting it. In our case this can create quite the memory leak...

Here is the key retention (ignore the right one, that was in my code and I already fixed it):
![image](https://cloud.githubusercontent.com/assets/10047833/11846133/d7fba55e-a41f-11e5-9bd2-b492fb9b5fc5.png)

I would love to receive some input on how to fix this issue.

Cheers.

**Comment by gabikliot** [comment]
Good point.
In general this could be fixed by adding `IntValueStatistic.Delete` (`IntValueStatistic` does not have `Delete` now, but it can be done the same as `CounterStatistic` is doing it now)  and calling it in agent's `Shutdown` method.

But in this particular, this line was already removed recently in https://github.com/dotnet/orleans/pull/1093. Look at the latest code.

**Comment by jason-bragg** [comment]
If you want to change this in your code without Orleans changes, You could take advantage of the fact that Caches and Receivers are coupled.  That is, a pulling agent will use both a cache for a queue and it's receiver or neither.  This fact makes it safe to dispose of a cache related to a queue when the receiver is shutdown.  In disposing of the cache object, all the heavy resources can be freed.  You'll still have an object leak for the disposed cache, but it will be harmless.

**Comment by gabikliot** [comment]
Closing this, since the issue has already been fixed in  #1093.

**Comment by randa1** [comment]
@gabikliot It didn't fix it. There's another problematic line in the same method:
```
IntValueStatistic.FindOrCreate(new StatisticName(StatisticNames.STREAMS_PERSISTENT_STREAM_PUBSUB_CACHE_SIZE, statUniquePostfix), () => pubSubCache.Count);
```

This creates a closure to the `PersistentStreamPullingAgent` which means it will never be released, thus preventing the release of the cache too.

**Comment by gabikliot** [comment]
I think I fixed that line already in #1166.
Can you please double check with the latest code?

**Comment by gabikliot** [comment]
Closing this again, since the issue has already been fixed in #1093 and in #1166.
@randa1 , feel free to re-open if the issue persists.
