### ISSUE TITLE
Code generation does not work with generic type constraints

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#1192]
Hi folks,

I have the following grain interface:

```csharp
public interface ISessionGrain<TData> : IGrainWithStringKey
  where TData : class
```

Code generation works perfectly with Orleans 1.0.10, but with 1.1.0 I get the follwing compile time error in orleans.codegen.cs:

*CS0452: The type 'TData' must be a reference type in order to use it as parameter 'TData' in the generic type or method 'ISessionGrain<TData>'.*

Here is the location the error occurs:

```csharp
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.1.0.0"), global::System.SerializableAttribute, global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute, global::Orleans.CodeGeneration.GrainReferenceAttribute(typeof (global::Implico.Microservices.Sessions.Grains.ISessionGrain<>))]
internal class OrleansCodeGenSessionGrainReference<TData> : global::Orleans.Runtime.GrainReference, global::Implico.Microservices.Sessions.Grains.ISessionGrain<TData>
{
  //...
}
```

The error is that the generic type constraints are not generated into the code.

Cheers
Peter

**Comment by ReubenBond** [comment]
Hi Peter,
This was solved by #1137 and I have increased test coverage to specifically include the `class` constraint. Apologies for not having this in the v1.1.0 release. The next release will improve support for type constraints via #1137 and #1178.

**Comment by peter-perot** [comment]
Hi Reuben, thank you. Sorry for overlooking the original issue already posted. Will stay on 1.0.10 until the bug is fixed in the next release.

**Comment by peter-perot** [comment]
Updated to Orleans 1.1.1.0, but the bug still exists: no generic type constraints are generated.

My grain interface:

````csharp
public interface IAuthenticationService<TCredentials>
	where TCredentials : IAuthenticationCredentials
{
	Task<ISession> LogIn(TCredentials credentials, TimeSpan expirationTime, string sessionId = null, bool bypassAuthentication = false);

	Task LogOut(ISession session);
}
````

The generated code:

````csharp
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.1.1.0"), global::System.SerializableAttribute, global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute, global::Orleans.CodeGeneration.GrainReferenceAttribute(typeof (global::Implico.Microservices.Security.Grains.IAuthenticationServiceGrainBase<>))]
internal class OrleansCodeGenAuthenticationServiceGrainBaseReference<TCredentials> : global::Orleans.Runtime.GrainReference, global::Implico.Microservices.Security.Grains.IAuthenticationServiceGrainBase<TCredentials>
{
````

As you can see: Still no type constraints.

**Comment by ReubenBond** [comment]
Why is a grain reference being generated at all in that case?

**Comment by peter-perot** [comment]
Don't know. I just created a simple grain interface project with only the following code:

````csharp
using Orleans;

namespace GrainInterfaces
{
	public interface IAuthenticationGrain<TCredentials> : IGrainWithIntegerKey
		where TCredentials : Credentials
	{
	}

	public class Credentials
	{
	}
}
````

The orleans.codegen.cs file which does not compile:

````csharp
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 414
#pragma warning disable 649
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998
[assembly: global::System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.1.1.0")]
[assembly: global::Orleans.CodeGeneration.OrleansCodeGenerationTargetAttribute("GrainInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")]
namespace GrainInterfaces
{
    using global::Orleans.Async;
    using global::Orleans;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.1.1.0"), global::System.SerializableAttribute, global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute, global::Orleans.CodeGeneration.GrainReferenceAttribute(typeof (global::GrainInterfaces.IAuthenticationGrain<>))]
    internal class OrleansCodeGenAuthenticationGrainReference<TCredentials> : global::Orleans.Runtime.GrainReference, global::GrainInterfaces.IAuthenticationGrain<TCredentials>
    {
        protected @OrleansCodeGenAuthenticationGrainReference(global::Orleans.Runtime.GrainReference @other): base (@other)
        {
        }

        protected @OrleansCodeGenAuthenticationGrainReference(global::System.Runtime.Serialization.SerializationInfo @info, global::System.Runtime.Serialization.StreamingContext @context): base (@info, @context)
        {
        }

        protected override global::System.Int32 InterfaceId
        {
            get
            {
                return 1173595186;
            }
        }

        public override global::System.String InterfaceName
        {
            get
            {
                return "global::GrainInterfaces.IAuthenticationGrain<TCredentials>";
            }
        }

        public override global::System.Boolean @IsCompatible(global::System.Int32 @interfaceId)
        {
            return @interfaceId == 1173595186 || @interfaceId == -2117557289;
        }

        protected override global::System.String @GetMethodName(global::System.Int32 @interfaceId, global::System.Int32 @methodId)
        {
            switch (@interfaceId)
            {
                case -2117557289:
                    switch (@methodId)
                    {
                        default:
                            throw new global::System.NotImplementedException("interfaceId=" + -2117557289 + ",methodId=" + @methodId);
                    }

                case 1173595186:
                    switch (@methodId)
                    {
                        default:
                            throw new global::System.NotImplementedException("interfaceId=" + 1173595186 + ",methodId=" + @methodId);
                    }

                default:
                    throw new global::System.NotImplementedException("interfaceId=" + @interfaceId);
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.1.1.0"), global::Orleans.CodeGeneration.MethodInvokerAttribute("global::GrainInterfaces.IAuthenticationGrain<TCredentials>", 1173595186, typeof (global::GrainInterfaces.IAuthenticationGrain<>)), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    internal class OrleansCodeGenAuthenticationGrainMethodInvoker<TCredentials> : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        public global::System.Threading.Tasks.Task<global::System.Object> @Invoke(global::Orleans.Runtime.IAddressable @grain, global::System.Int32 @interfaceId, global::System.Int32 @methodId, global::System.Object[] @arguments)
        {
            try
            {
                if (@grain == null)
                    throw new global::System.ArgumentNullException("grain");
                switch (@interfaceId)
                {
                    case -2117557289:
                        switch (@methodId)
                        {
                            default:
                                throw new global::System.NotImplementedException("interfaceId=" + -2117557289 + ",methodId=" + @methodId);
                        }

                    case 1173595186:
                        switch (@methodId)
                        {
                            default:
                                throw new global::System.NotImplementedException("interfaceId=" + 1173595186 + ",methodId=" + @methodId);
                        }

                    default:
                        throw new global::System.NotImplementedException("interfaceId=" + @interfaceId);
                }
            }
            catch (global::System.Exception exception)
            {
                return global::Orleans.Async.TaskUtility.@Faulted(exception);
            }
        }

        public global::System.Int32 InterfaceId
        {
            get
            {
                return 1173595186;
            }
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 649
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
````

**Comment by ReubenBond** [comment]
Ah, ok. The interface in the second post differs from the first. I'll check it out when I get to a PC

**Comment by peter-perot** [comment]
Thanks in advance. Yes, the first code sample is from production code. It's easier to reproduce the issue with the second sample because all you have to do is pasting the code into a fresh grain interface project.

**Comment by ReubenBond** [comment]
It looks like the fix didn't make it into the v1.1.1 branch. v1.1.1 was a patch which only included a tiny fix to a critical issue. The fix will be included in the next release. Apologies for the inconvenience, Peter

**Comment by mauriciomagni** [comment]
Hello 
It seems I am run into this issue.
My interface defines:
Task<TCommand> ExecuteCommand<TCommand>(TCommand Command) where TCommand : VCommand;
but in Orleans.codegen.cs appears:
        public global::System.Threading.Tasks.Task<TCommand> @ExecuteCommand(TCommand @Command)
        {
As you can see, the generic type is missed in the method definition and the constraint is gone.
I imagine I am missing something, could you please, point me in the right direction to fix this?
Thank you,
Mauricio.
