### ISSUE TITLE
【V3.1.0-rc1】 Orleans.CodeGenerator failed

### ISSUE THREAD

**Issue by lfzm** [dotnet/orleans#6296]
Upgrade to V3.1.0-rc1 based on [Orleans.MultiClient failed](https://github.com/lfzm/Orleans.MultiClient)

```
1> ------ Started all regeneration: Project: Orleans.Grain, Configuration: Debug Any CPU ------
1> Orleans.CodeGenerator-command-line = SourceToSource D: \ Work \ Orleans.MultiClient \ example \ Orleans.Grain \ obj \ Debug \ netstandard2.0 \ Orleans.Grain.orleans.g.args.txt
1>-Code Generation FAILED-
1>
1> Exc level 0: System.InvalidOperationException: Unable to find type with metadata name "System.Threading.Tasks.ValueTask".
1> at Orleans.CodeGenerator.WellKnownTypes. <FromCompilation> g__Type | 0_0 (String type, <> c__DisplayClass0_0 &) in D: \ build \ agent \ _work \ 25 \ s \ src \ Orleans.CodeGenerator \ WellKnownTypes.cs: line 119
1> at Orleans.CodeGenerator.WellKnownTypes.FromCompilation (Compilation compilation) in D: \ build \ agent \ _work \ 25 \ s \ src \ Orleans.CodeGenerator \ WellKnownTypes.cs: line 13
1> at Orleans.CodeGenerator.CodeGenerator..ctor (Compilation compilation, CodeGeneratorOptions options, ILogger log) in D: \ build \ agent \ _work \ 25 \ s \ src \ Orleans.CodeGenerator \ CodeGenerator.cs: line 39
1> at Orleans.CodeGenerator.MSBuild.CodeGeneratorCommand.Execute (CancellationToken cancellationToken) in D: \ build \ agent \ _work \ 25 \ s \ src \ Orleans.CodeGenerator.MSBuild \ CodeGeneratorCommand.cs: line 143
1> at Microsoft.Orleans.CodeGenerator.MSBuild.Program.SourceToSource (String [] args) in D: \ build \ agent \ _work \ 25 \ s \ src \ Orleans.CodeGenerator.MSBuild \ Program.cs: line 138
1> at Microsoft.Orleans.CodeGenerator.MSBuild.Program.Main (String [] args) in D: \ build \ agent \ _work \ 25 \ s \ src \ Orleans.CodeGenerator.MSBuild \ Program.cs: line 26
1> C: \ Users \ Lfzm \ .nuget \ packages \ microsoft.orleans.codegenerator.msbuild \ 3.1.0-rc1 \ build \ Microsoft.Orleans.CodeGenerator.MSBuild.targets (125,5): error MSB3073: Command " "dotnet" "C: \ Users \ Lfzm \ .nuget \ packages \ microsoft.orleans.codegenerator.msbuild \ 3.1.0-rc1 \ build \ .. \ tasks \ netcoreapp3.1 \ Orleans.CodeGenerator.MSBuild.dll" SourceToSource "D: \ Work \ Orleans.MultiClient \ example \ Orleans.Grain \ obj \ Debug \ netstandard2.0 \ Orleans.Grain.orleans.g.args.txt" "exited with code 3.
1> The operation of generating the project "Orleans.Grain.csproj" has been completed-failed.
=========== Regenerate all: 0 successes, 1 failure, 0 skips ===========
```

**Comment by sergeybykov** [comment]
Looks like the codegen brings a dependency on `System.Threading.Tasks.Extensions`, and unless the target project references it, build fails. As a workaround, you can add `System.Threading.Tasks.Extensions` to `Orleans.Grain` and 'Orleans.Grain2` project for now. But we need to fix this.

**Comment by benjaminpetit** [comment]
I think we need to add `System.Threading.Tasks.Extensions` as a dependency on `Orleans.CodeGenerator`, since this project try to resolve the `ValueType` type by string.

Testing it right now and will submit a PR ASAP

**Comment by sergeybykov** [comment]
I suspect this is because of #6285.

**Comment by sergeybykov** [comment]
Resolved via #6297.

**Comment by sergeybykov** [comment]
We published [3.1.0-rc2](https://github.com/dotnet/orleans/releases/tag/v3.1.0-rc2) with the fix.

**Comment by lfzm** [comment]
@sergeybykov  I tested and found that v3.1.0-rc2 did not solve the problem, unfortunately.

**Comment by sergeybykov** [comment]
That's odd. Thanks for validating!

**Comment by sergeybykov** [comment]
We just published 3.1.0-rc3 to nuget.org that should fix this for real.

**Comment by sergeybykov** [comment]
Resolved via #6301.

**Comment by lfzm** [comment]
Thank you for your efforts, I verified successfully
